# Autogenerated by nbdev

d = { 'settings': { 'doc_baseurl': '/meme-games',
                'doc_host': 'https://ssslakter.github.io',
                'git_url': 'https://github.com/ssslakter/meme-games',
                'lib_path': 'meme_games'},
  'syms': {}}
