services:
  app:
    image: ghcr.io/ssslakter/meme-games:main
    pull_policy: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./user-content:/app/user-content
    restart: always