[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "meme-games"
version = "0.1.0"
description = "A collection of meme games"
authors = [
    { name="Slava Chaunin", email="slava.chaunin@gmail.com" }
]
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "python-fasthtml"
]


[tool.setuptools]
packages = ["meme_games"]