# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/wordpack.ipynb.

# %% auto 0
__all__ = ['WordPack', 'WordPackManager']

# %% ../../../notebooks/wordpack.ipynb 1
from ...core import *

@dataclass
class WordPack(Model):
    name: str
    words_: str # \n separated words
    id: str = field(default_factory=random_id)
    created_at: dt.datetime = field(default_factory=dt.datetime.now)
    
    def __post_init__(self):
        if isinstance(self.words_, list): self.words_ = '\n'.join(self.words_)
    @property
    def words(self):
        return self.words_.split('\n')


class WordPackManager(DataManager[WordPack]):
    def _set_tables(self):
        self.words = self.db.t.wordpacks.create(WordPack.columns(), pk='id', if_not_exists=True)
        return self.words

    def get_all(self):
        return list(map(WordPack.from_cols, self.db.q(f'select {mk_aliases(WordPack, self.table)} from {self.table}')))
    
    def get_by_id(self, id: str):
        return WordPack.from_dict(self.words.get(id))
    
