# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/wordpack.ipynb.

# %% auto 0
__all__ = ['WordPack', 'WordPackRepo']

# %% ../../../notebooks/wordpack.ipynb 1
from ...core import *
from ...domain import *

@dataclass
class WordPack(Model):
    _ignore = ('author')

    name: str = 'Empty Pack'
    words_: str = '' # \n separated words
    author: Optional[User] = None
    author_id: str = ''
    id: str = field(default_factory=random_id)
    created_at: dt.datetime = field(default_factory=dt.datetime.now)
    
    def __post_init__(self):
        if isinstance(self.words_, list): self.words_ = '\n'.join(self.words_)
    
    @property
    def words(self):
        return self.words_.split('\n')
    
    def get_author_name(self) -> Optional[str]:
        return self.author.name if self.author else None

    
    @classmethod
    def from_cols(cls, cols: dict):
        d = cols2dict(cols)
        if d[cls]['author_id']:
            d[cls]['author'] = User.from_dict(d.pop(User))
        return cls.from_dict(d[cls])


class WordPackRepo(DataRepository[WordPack]):
    def _set_tables(self):
        self.wordpacks = self.db.t.wordpacks.create(WordPack.columns(), pk='id', transform=True)
        self.users = self.db.t.user

        self.qry_template = f"""
        select {mk_aliases(WordPack, self.wordpacks)},
        {mk_aliases(User, self.users)}
        from {self.wordpacks} left join {self.users}
        on {self.wordpacks.c.author_id} = {self.users.c.uid}
        """
        return self.wordpacks
    
    def __post_init__(self):
        self.init_defaults()
        
    def get_all(self, offset: int = 0, limit: int = 100):
        qry = f"{self.qry_template} limit {limit} offset {offset}"
        return list(map(WordPack.from_cols, self.db.q(qry)))
    
    
    def get_by_id(self, id: str):
        if id not in self.table: return None
        return WordPack.from_dict(self.table.get(id))
    

    def find(self, name: str) -> Optional[WordPack]:
        '''Finds a wordpack by its name.'''
        res = self.db.q(f"{self.qry_template} where {self.table.c.name} like ?", [name])
        return WordPack.from_cols(res[0]) if res else None
    

    def init_defaults(self):
        if self.find('default'): return
        packs = [
            WordPack(name='Default', words_='apple\nbanana\ncherry\norange\npear'),
        ]
        self.upsert_all(packs)
