# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/user.ipynb.

# %% auto 0
__all__ = ['User', 'UserManager', 'user_beforeware', 'UserName']

# %% ../../notebooks/user.ipynb 1
import time
from functools import wraps
from dataclasses import dataclass
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
import fastlite as fl
import fastcore.all as fc
from .utils import *
from .database import *

# %% ../../notebooks/user.ipynb 2
@dataclass
class User(Model):
    uid: str
    name: str
    filename: Optional[str] = None

    async def set_picture(self, file: UploadFile, content_path='./user-content'):
        self.reset_picture(content_path)
        fname = f"{self.uid}_{time.time()}.{file.filename.split('.')[-1]}"
        dir = Path(content_path)
        dir.mkdir(parents=True, exist_ok=True)
        with open(dir/fname, 'wb') as f: f.write(await file.read())
        self.filename = str(fname)

    def reset_picture(self, content_path='./user-content'):
        if not self.filename: return
        path = Path(content_path)/self.filename
        path.unlink(missing_ok=True)
        self.filename = None
        
    def __eq__(self, value: 'User'): return self.uid == value.uid

# %% ../../notebooks/user.ipynb 3
class UserManager(DataManager):
    def _set_tables(self): 
        self.db.create(User, pk='uid', transform=True)
        self.users: fl.Table = self.db.t.user
        return self.users
    
    def create(self, uid: str=None, name: str = 'null'):
        u = User(uid or random_id(), name)
        self.users.insert(u)
        return u
    
    def get(self, uid: str): return self.users.get(uid)
    def update(self, user: User): return self.users.update(user)
    
    def get_or_create(self, sess: dict, name: str = 'null') -> User:
        sess = sess['session'] if 'session' in sess else sess
        uid = sess.setdefault('uid', random_id())
        if uid in self.users: return self.users[uid]
        return self.create(uid, name)

# %% ../../notebooks/user.ipynb 4
def user_beforeware(manager: UserManager, skip=None):
    '''Makes sure that request always contains valid user'''
    def before(req: Request): req.state.user = manager.get_or_create(req.session)
    return Beforeware(before, skip)

# %% ../../notebooks/user.ipynb 5
def UserName(r: User, u: User, is_connected=True, cls='username', **kwargs):
    cls += ' muted' if not is_connected else ''
    return Span(B(u.name) if r==u else u.name, data_username = u.uid, cls=cls, **kwargs, hx_swap_oob=f"outerHTML:span[data-username='{u.uid}']")
