# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/whoami.ipynb.

# %% auto 0
__all__ = ['WAILobby', 'PlayerLabel', 'WhoAmIPlayer', 'WhoAmIManager']

# %% ../../notebooks/whoami.ipynb 1
from ..common import *

# %% ../../notebooks/whoami.ipynb 2
@dataclass
class PlayerLabel:
    x: int = 0
    y: int = 0
    width: int = 0
    height: int = 0


@dataclass
class WhoAmIPlayer(LobbyMember):
    _ignore = LobbyMember._ignore + ('label_tfm',)
    label_text: str = ''
    label_tfm: Optional[PlayerLabel] = None
    notes: str = ''

    def set_notes(self, notes: str): self.notes = notes
    def set_label(self, label: str): self.label_text = label
    def set_label_transform(self, tfm: dict): self.label_tfm = PlayerLabel(**tfm)
    
WAILobby = Lobby[WhoAmIPlayer]

# %% ../../notebooks/whoami.ipynb 4
class WhoAmIManager(DataManager[WhoAmIPlayer]):
    def __init__(self, member_manager: MemberManager):
        self.mm = member_manager
        super().__init__(member_manager.db)
    
    def _set_tables(self):
        new_cols = dict(set(WhoAmIPlayer.columns().items()) - set(LobbyMember.columns().items()))
        for c in new_cols.items(): self.mm.members.add_column(*c)
        return self.mm.members
    
    def get_all(self, lobby_id: str) -> list[WhoAmIPlayer]: 
        return [WhoAmIPlayer.convert(m) for m in self.mm.get_all(lobby_id)]
