name: deploy

on:
  push:
    branches:
      - main   # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    if: ${{ ! contains(github.event.head_commit.message, '[no-deploy]') }}
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d --build