name: deploy

on:
  push:
    branches:
      - main   # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: docker compose up -d --build