name: Generate requirements.txt

on:
  push:
    branches:
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up Git
      run: |  
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Generate requirements.txt
      run: |
        pip-compile pyproject.toml -o requirements.txt

    - name: Commit and push changes
      run: |
        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update dependencies"
          git push
        fi
